# Define example data
COLUMN_NAME_LIST = [
    'shot_id',
    'sequence',
    'status',
    'start_date',
    'due_date',
    'priority',
    'shot_length',
    'artist',
    'department',
]

COLUMN_NAME_VFX_ASSET_LIST = [
    'asset_id',
    'asset_name',
    'status',
    'start_date',
    'due_date',
    'priority',
    'artist',
    'department',
    'file_path',  # Added to include the path where the asset files are stored
]

ID_TO_DATA_DICT = {
    1: {
        'shot_id': 'SHOT001',
        'sequence': 'SEQ001',
        'status': 'In Progress',
        'start_date': '2023-06-17',
        'due_date': '2023-07-15',
        'priority': 2,
        'shot_length': 150,
        'artist': 'John Smith',
        'department': 'Compositing'
    },
    2: {
        'shot_id': 'SHOT002',
        'sequence': 'SEQ001',
        'status': 'Completed',
        'start_date': '2023-06-20',
        'due_date': '2023-07-10',
        'priority': 1,
        'shot_length': 200,
        'artist': 'Jane Doe',
        'department': 'Animation'
    },
    3: {
        'shot_id': 'SHOT003',
        'sequence': 'SEQ002',
        'status': 'Not Started',
        'start_date': '2023-06-25',
        'due_date': '2023-07-20',
        'priority': 3,
        'shot_length': 120,
        'artist': 'Alex Johnson',
        'department': 'Lighting'
    },
    4: {
        'shot_id': 'SHOT004',
        'sequence': 'SEQ002',
        'status': 'In Progress',
        'start_date': '2023-06-18',
        'due_date': '2023-07-25',
        'priority': 2,
        'shot_length': 180,
        'artist': 'Emily Brown',
        'department': 'Modeling'
    },
    5: {
        'shot_id': 'SHOT005',
        'sequence': 'SEQ003',
        'status': 'Completed',
        'start_date': '2023-06-22',
        'due_date': '2023-07-12',
        'priority': 1,
        'shot_length': 250,
        'artist': 'Michael Johnson',
        'department': 'Rigging'
    },
    6: {
        'shot_id': 'SHOT006',
        'sequence': 'SEQ003',
        'status': 'In Progress',
        'start_date': '2023-06-30',
        'due_date': '2023-07-30',
        'priority': 3,
        'shot_length': 130,
        'artist': 'Sophia Wilson',
        'department': 'Texturing'
    },
    7: {
        'shot_id': 'SHOT007',
        'sequence': 'SEQ004',
        'status': 'Not Started',
        'start_date': '2023-06-16',
        'due_date': '2023-07-18',
        'priority': 2,
        'shot_length': 160,
        'artist': 'Daniel Lee',
        'department': 'Animation'
    },
    8: {
        'shot_id': 'SHOT008',
        'sequence': 'SEQ004',
        'status': 'In Progress',
        'start_date': '2023-06-25',
        'due_date': '2023-07-25',
        'priority': 2,
        'shot_length': 190,
        'artist': 'Olivia Davis',
        'department': 'Compositing'
    },
    9: {
        'shot_id': 'SHOT009',
        'sequence': 'SEQ005',
        'status': 'In Progress',
        'start_date': '2023-06-19',
        'due_date': '2023-07-20',
        'priority': 3,
        'shot_length': 140,
        'artist': 'Noah Johnson',
        'department': 'Lighting'
    },
    10: {
        'shot_id': 'SHOT010',
        'sequence': 'SEQ005',
        'status': 'Completed',
        'start_date': '2023-06-20',
        'due_date': '2023-07-15',
        'priority': 1,
        'shot_length': 220,
        'artist': 'Isabella Clark',
        'department': 'Modeling'
    },
}

ID_TO_VFX_DATA_DICT = {
    1: {
        'asset_id': 'MODEL001',
        'asset_name': 'Dragon_Model',
        'status': 'In Progress',
        'start_date': '2023-06-17',
        'due_date': '2023-07-15',
        'priority': 2,
        'artist': 'John Smith',
        'department': 'Modeling',
        'file_path': '/projects/seq001/shots/shot001/modeling/dragon_model_v001.ma'
    },
    2: {
        'asset_id': 'TEXTURE002',
        'asset_name': 'Dragon_Texture',
        'status': 'Completed',
        'start_date': '2023-06-20',
        'due_date': '2023-07-10',
        'priority': 1,
        'artist': 'Jane Doe',
        'department': 'Texturing',
        'file_path': 'blackboard/examples/image_not_available_placeholder.png'
    },
    3: {
        'asset_id': 'ANIM003',
        'asset_name': 'Dragon_Animation',
        'status': 'Not Started',
        'start_date': '2023-06-25',
        'due_date': '2023-07-20',
        'priority': 3,
        'artist': 'Alex Johnson',
        'department': 'Animation',
        'file_path': '/projects/seq001/shots/shot001/animation/dragon_anim_v001.ma'
    },
    4: {
        'asset_id': 'COMP004',
        'asset_name': 'Dragon_Composite',
        'status': 'In Progress',
        'start_date': '2023-06-18',
        'due_date': '2023-07-25',
        'priority': 2,
        'artist': 'Emily Brown',
        'department': 'Compositing',
        'file_path': '/projects/seq001/shots/shot001/compositing/dragon_comp_v001.nk'
    },
    5: {
        'asset_id': 'RIG005',
        'asset_name': 'Dragon_Rig',
        'status': 'Completed',
        'start_date': '2023-06-22',
        'due_date': '2023-07-12',
        'priority': 1,
        'artist': 'Michael Johnson',
        'department': 'Rigging',
        'file_path': '/projects/seq001/shots/shot001/rigging/dragon_rig_v002.ma'
    },
    6: {
        'asset_id': 'LIGHT006',
        'asset_name': 'Dragon_Lighting',
        'status': 'In Progress',
        'start_date': '2023-06-30',
        'due_date': '2023-07-30',
        'priority': 3,
        'artist': 'Sophia Wilson',
        'department': 'Lighting',
        'file_path': '/projects/seq001/shots/shot001/lighting/dragon_light_v001.abc'
    }
}

VFX_DATA_DICTS = [
    {'artist': 'John Smith',
    'asset_id': 'MODEL001',
    'asset_name': 'Dragon_Model',
    'department': 'Modeling',
    'due_date': '2023-07-15',
    'file_path': '/projects/seq001/shots/shot001/modeling/dragon_model_v001.ma',
    'priority': 2,
    'start_date': '2023-06-17',
    'status': 'In Progress'},
    {'artist': 'Jane Doe',
    'asset_id': 'TEXTURE002',
    'asset_name': 'Dragon_Texture',
    'department': 'Texturing',
    'due_date': '2023-07-10',
    'file_path': 'blackboard/examples/image_not_available_placeholder.png',
    'priority': 1,
    'start_date': '2023-06-20',
    'status': 'Completed'},
    {'artist': 'Alex Johnson',
    'asset_id': 'ANIM003',
    'asset_name': 'Dragon_Animation',
    'department': 'Animation',
    'due_date': '2023-07-20',
    'file_path': '/projects/seq001/shots/shot001/animation/dragon_anim_v001.ma',
    'priority': 3,
    'start_date': '2023-06-25',
    'status': 'Not Started'},
    {'artist': 'Emily Brown',
    'asset_id': 'COMP004',
    'asset_name': 'Dragon_Composite',
    'department': 'Compositing',
    'due_date': '2023-07-25',
    'file_path': '/projects/seq001/shots/shot001/compositing/dragon_comp_v001.nk',
    'priority': 2,
    'start_date': '2023-06-18',
    'status': 'In Progress'},
    {'artist': 'Michael Johnson',
    'asset_id': 'RIG005',
    'asset_name': 'Dragon_Rig',
    'department': 'Rigging',
    'due_date': '2023-07-12',
    'file_path': '/projects/seq001/shots/shot001/rigging/dragon_rig_v002.ma',
    'priority': 1,
    'start_date': '2023-06-22',
    'status': 'Completed'},
    {'artist': 'Sophia Wilson',
    'asset_id': 'LIGHT006',
    'asset_name': 'Dragon_Lighting',
    'department': 'Lighting',
    'due_date': '2023-07-30',
    'file_path': '/projects/seq001/shots/shot001/lighting/dragon_light_v001.abc',
    'priority': 3,
    'start_date': '2023-06-30',
    'status': 'In Progress'},
]
